# Generated by Django 4.2 on 2023-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20210512_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
