# Generated by Django 4.2 on 2023-04-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
